name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: boolean
        description: Destroy environment?
        required: true
        default: false
  pull_request:
    paths:
    - infra/**
  push:
    branches:
    - none

env:
  tf_actions_working_dir: infra
  
#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write


jobs: 
  plan:	
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: tfplan
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    
    steps:
    - uses: actions/checkout@v2
    - name: List files in the current directory
      run: |
        pwd
        ls -l
    - name: Recursively List files in the github.workspace
      run: |
        ls -lR ${{ github.workspace }}
        
    - name: Job Status
      run: echo "🍏 This job's status is ${{ job.status }}."
        
    - name: NOT Print a secret value
      run: echo "🍏 Client Id is ${{ secrets.AZURE_AD_CLIENT_ID }}."
    
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az --version
          #az account show
          # You can write your Azure CLI inline scripts here.
           
    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
 
    #- name: Init TFLint
      #run: tflint --init
 
    #- name: Run TFLint
      #run: tflint -f compact
    
    - name: Calculate destroy arg
      id: destroy_arg
      run: |
        if [ $DESTROY == "true" ]; then
          echo "::set-output name=val::-destroy" 
        else
          echo "::set-output name=val:: "
        fi
      env:
        DESTROY: ${{ github.event.inputs.destroy }}

    - name: Terraform Plan
      id: plan
      run: terraform plan $DESTROY -no-color --out=tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true
        DESTROY: ${{ steps.destroy_arg.outputs.val }}
        
    - name: List files in the current directory (after plan)
      run: |
        pwd
        ls -l

    - name: Create the plan summary
      uses: actions/github-script@v6
      if: always()
      id: summary
      env:
        PLAN: '${{ steps.plan.outputs.stdout }}'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 1. Prep the output
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          
          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          
          // 2. Set the output variable
          const fs = require('fs');
          fs.writeFileSync('${{ env.tf_actions_working_dir }}/summary.md', output);
          core.setOutput('summary', output);
      
    - name: Write the step summary
      if: always()
      run: cat summary.md >> $GITHUB_STEP_SUMMARY

    - name: Terraform Plan Output to txt
      id: planout
      run: terraform show -no-color tfplan > tfplan.txt
      
    - name: Upload the plan as tfplan.txt file
      uses: actions/upload-artifact@v4
      with:
        name: tfplan.txt
        path: ${{ env.tf_actions_working_dir }}/tfplan.txt
      
    - name: Upload the plan as tfplan file
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ${{ env.tf_actions_working_dir }}/tfplan
        
    - name: List files in the  directory (after plan)
      run: |
        pwd
        ls -ltra ..
        
    - name: Recursively List files in the github.workspace
      run: |
        ls -laR ${{ github.workspace }}
      
    - name: Upload the .terraform.lock.hcl file
      uses: actions/upload-artifact@v4
      with:
        name: lock
        path: ${{ env.tf_actions_working_dir }}/.terraform.lock.hcl

    - name: Publish plan as a status
      if: github.event_name == 'pull_request'
      uses: Sibz/github-status-action@v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        state: ${{ steps.summary.outputs.summary }}
        context: Terraform Plan
        description: Terraform Plan Summary
        sha: ${{ github.event.pull_request.head.sha }}

  apply:
    needs: plan
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: tfplan
    
    steps:
    - uses: actions/checkout@v2
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
        ls -lR ${{ github.workspace }}
        
    - name: Job Status
      run: echo "🍏 This job's status is ${{ job.status }}."
        
    - name: NOT Print a secret value
      run: echo "🍏 Client Id is ${{ secrets.AZURE_AD_CLIENT_ID }}."
    
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az --version
          #az account show
          # You can write your Azure CLI inline scripts here.
           
    # Install the latest version of the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
           
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true

    # Download saved plan from artifacts  
    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        
    # Download saved .terraform.lock.hcl from artifacts  
    - name: Download Terraform terraform.lock.hclan
      uses: actions/download-artifact@v4
      with:
        name: lock
        
    - name: List files in the directroy
      run: |
        pwd
        ls -lt
        
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true


        
